// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/0vkanix/greenlight/internal/movie/types"
	"github.com/google/uuid"
)

type Movie struct {
	ID        uuid.UUID     `json:"id"`
	CreatedAt time.Time     `json:"created_at"`
	Title     string        `json:"title"`
	Year      int           `json:"year,omitzero"`
	Runtime   types.Runtime `json:"runtime,omitzero"`
	Genres    []string      `json:"genres,omitzero"`
	Version   int           `json:"version"`
}
