// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package movie

import (
	"time"

	"github.com/google/uuid"
)

type Movie struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"-"`
	Title     string    `json:"title"`
	Year      int32     `json:"year,omitzero"`
	Runtime   Runtime   `json:"runtime,omitzero"`
	Genres    []string  `json:"genres,omitzero"`
	Version   int32     `json:"version"`
}
