// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package movie

import (
	"context"

	"github.com/google/uuid"
)

const get = `-- name: Get :one
SELECT id, created_at, title, year, runtime, genres, version
FROM movies
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Genres,
		&i.Version,
	)
	return i, err
}

const insert = `-- name: Insert :one
INSERT INTO movies (title, year, runtime, genres)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, title, year, runtime, genres, version
`

type InsertParams struct {
	Title   string   `json:"title"`
	Year    int32    `json:"year,omitzero"`
	Runtime Runtime  `json:"runtime,omitzero"`
	Genres  []string `json:"genres,omitzero"`
}

func (q *Queries) Insert(ctx context.Context, arg InsertParams) (Movie, error) {
	row := q.db.QueryRow(ctx, insert,
		arg.Title,
		arg.Year,
		arg.Runtime,
		arg.Genres,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Title,
		&i.Year,
		&i.Runtime,
		&i.Genres,
		&i.Version,
	)
	return i, err
}
